import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { catchError, finalize, forkJoin, of, switchMap } from 'rxjs';
import { LucideAngularModule } from 'lucide-angular';
import { AuthService } from '../../services/auth.service';
import { DashboardHealth, PredictionDashboard, PredictionHorizon, SupplyRecommendation } from '../../models/prediction-dashboard.model';
import { PredictionDashboardService } from '../../services/prediction-dashboard.service';

const DOWN: DashboardHealth = { java_api: { status: 'DOWN' }, fastapi: { status: 'DOWN' }, database: { status: 'DOWN' } };

@Component({
  selector: 'app-dashboard', standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  template: `
  <div class="space-y-6">
    <header class="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
      <div><h2 class="text-2xl font-bold text-brand-dark">Dashboard</h2><p class="text-gray-500">Estado de abastecimiento y resumen predictivo</p></div>
      <div class="flex flex-wrap items-center gap-2">
        <select [(ngModel)]="selectedDate" (ngModelChange)="loadDashboard()" [disabled]="loading || !dates.length" class="rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm text-brand-dark"><option *ngFor="let date of dates" [value]="date">{{ formatDate(date) }}</option></select>
        <span class="rounded-full px-3 py-1 text-xs font-medium" [ngClass]="health.java_api.status === 'UP' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-600'">Java API: {{ health.java_api.status === 'UP' ? 'conectada' : 'sin conexión' }}</span>
        <span class="rounded-full px-3 py-1 text-xs font-medium" [ngClass]="health.fastapi.status === 'UP' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-600'">FastAPI: {{ health.fastapi.status === 'UP' ? 'activa' : 'inactiva' }}</span>
      </div>
    </header>
    <div *ngIf="error" class="flex items-center justify-between gap-3 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{{ error }}</span><button type="button" (click)="error = ''" aria-label="Cerrar">×</button></div>
    <section class="flex flex-col gap-3 border-y border-brand-wood/10 py-4 lg:flex-row lg:items-center lg:justify-between">
      <div class="flex items-center gap-2"><span class="text-sm font-medium text-gray-600">Horizonte:</span><button *ngFor="let horizon of horizons" type="button" (click)="selectHorizon(horizon)" class="rounded-lg border px-3 py-1.5 text-sm transition-colors" [ngClass]="selectedHorizon === horizon ? 'border-brand-terra bg-brand-terra text-white' : 'border-gray-200 bg-white text-gray-600 hover:border-brand-terra'">{{ horizon }} días</button></div>
      <div *ngIf="isAdmin" class="flex items-center gap-2"><label class="text-sm text-gray-600">Margen <input [(ngModel)]="safetyMargin" type="number" min="0" max="1" step="0.01" class="ml-1 w-20 rounded-lg border border-gray-200 px-2 py-1"></label><button type="button" (click)="updatePredictions()" [disabled]="updating || !selectedDate" class="inline-flex items-center gap-2 rounded-lg bg-brand-terra px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><lucide-icon name="brain-circuit" [size]="16"></lucide-icon>{{ updating ? 'Actualizando...' : 'Actualizar predicciones' }}</button></div>
    </section>
    <section *ngIf="data as dashboard; else empty" class="space-y-6">
      <div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        <article class="border border-brand-wood/10 bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Insumos analizados</p><p class="mt-2 text-3xl font-bold text-brand-dark">{{ dashboard.indicadores.insumos_analizados }}</p><p class="mt-2 text-xs text-gray-500">Inventario considerado</p></article>
        <article class="border border-brand-wood/10 bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Requieren compra</p><p class="mt-2 text-3xl font-bold text-red-600">{{ dashboard.indicadores.requieren_compra }}</p><p class="mt-2 text-xs text-gray-500">{{ dashboard.indicadores.porcentaje_requieren_compra | number:'1.0-1' }}% del total</p></article>
        <article class="border border-brand-wood/10 bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Stock suficiente</p><p class="mt-2 text-3xl font-bold text-green-600">{{ dashboard.indicadores.stock_suficiente }}</p><p class="mt-2 text-xs text-gray-500">{{ dashboard.indicadores.porcentaje_stock_suficiente | number:'1.0-1' }}% del total</p></article>
        <article class="border border-brand-wood/10 bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">Margen de seguridad</p><p class="mt-2 text-3xl font-bold text-brand-dark">{{ dashboard.margen_seguridad * 100 | number:'1.0-0' }}%</p><p class="mt-2 text-xs text-gray-500">Modelo {{ dashboard.version_modelo }}</p></article>
      </div>
      <div class="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <section class="border border-brand-wood/10 bg-white p-5 shadow-sm xl:col-span-2"><div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h3 class="font-bold text-brand-dark">Consumo previsto por horizonte</h3><p class="text-sm text-gray-500">Top 8 insumos analizados</p></div><div class="flex gap-3 text-xs text-gray-500"><span><i class="mr-1 inline-block h-2 w-2 rounded-full bg-green-500"></i>3 días</span><span><i class="mr-1 inline-block h-2 w-2 rounded-full bg-amber-400"></i>7 días</span><span><i class="mr-1 inline-block h-2 w-2 rounded-full bg-brand-terra"></i>14 días</span></div></div><div class="overflow-x-auto"><div class="grid min-w-[560px] grid-cols-8 items-end gap-3 border-b border-l border-gray-200 bg-[repeating-linear-gradient(to_bottom,transparent_0,transparent_39px,#f1f1f1_40px)] px-3 pt-4" style="height: 250px"><div *ngFor="let item of chartItems" class="flex h-full min-w-0 flex-col justify-end"><div class="flex h-full items-end justify-center gap-1"><span class="w-3 rounded-t bg-green-500" [style.height.%]="barHeight(item.prediccion_3_dias)" [title]="item.prediccion_3_dias + ' ' + item.unidad"></span><span class="w-3 rounded-t bg-amber-400" [style.height.%]="barHeight(item.prediccion_7_dias)" [title]="item.prediccion_7_dias + ' ' + item.unidad"></span><span class="w-3 rounded-t bg-brand-terra" [style.height.%]="barHeight(item.prediccion_14_dias)" [title]="item.prediccion_14_dias + ' ' + item.unidad"></span></div><span class="mt-2 truncate text-center text-[10px] text-gray-600" [title]="item.nombre_insumo">{{ item.nombre_insumo }}</span></div></div></div></section>
        <section class="border border-brand-wood/10 bg-white p-5 shadow-sm"><h3 class="font-bold text-brand-dark">Estado de abastecimiento</h3><p class="mt-1 text-sm text-gray-500">Decisión para la fecha seleccionada</p><div class="mt-6 flex flex-col items-center gap-5 sm:flex-row sm:justify-center xl:flex-col"><div class="relative h-40 w-40 rounded-full" [style.background]="donutBackground"><div class="absolute inset-9 grid place-items-center rounded-full bg-white text-center"><strong class="block text-2xl text-brand-dark">{{ supplyTotal }}</strong><span class="text-[11px] text-gray-500">insumos</span></div></div><div class="space-y-4 text-sm"><div class="flex items-start gap-2"><i class="mt-1 inline-block h-2.5 w-2.5 rounded-full bg-red-500"></i><p><strong class="block text-brand-dark">Requiere compra</strong><span class="text-xs text-gray-500">{{ dashboard.estado_abastecimiento.requieren_compra }} insumos ({{ purchasePercent | number:'1.0-0' }}%)</span></p></div><div class="flex items-start gap-2"><i class="mt-1 inline-block h-2.5 w-2.5 rounded-full bg-green-500"></i><p><strong class="block text-brand-dark">Stock suficiente</strong><span class="text-xs text-gray-500">{{ dashboard.estado_abastecimiento.stock_suficiente }} insumos ({{ sufficientPercent | number:'1.0-0' }}%)</span></p></div></div></div></section>
      </div>
      <section class="border border-brand-wood/10 bg-white shadow-sm"><header class="flex flex-col gap-3 border-b border-gray-100 p-5 md:flex-row md:items-center md:justify-between"><div><h3 class="font-bold text-brand-dark">Recomendaciones de compra</h3><p class="text-sm text-gray-500">Actualizado {{ dashboard.ultima_actualizacion | date:'dd/MM/yyyy HH:mm' }}</p></div><button type="button" (click)="exportCsv()" class="inline-flex items-center gap-2 self-start rounded-lg border border-brand-wood/20 px-3 py-2 text-sm font-medium text-brand-wood"><lucide-icon name="file-text" [size]="16"></lucide-icon>Exportar CSV</button></header><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-brand-cream/40 text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Insumo</th><th class="px-5 py-3">Stock</th><th class="px-5 py-3">Predicción</th><th class="px-5 py-3">Compra</th><th class="px-5 py-3">Estado</th></tr></thead><tbody><tr *ngFor="let item of dashboard.recomendaciones.slice(0, 10)" class="border-t border-gray-100"><td class="px-5 py-3"><strong class="text-brand-dark">{{ item.nombre_insumo }}</strong><span class="block text-xs text-gray-500">{{ item.categoria_insumo || 'Sin categoría' }}</span></td><td class="px-5 py-3">{{ item.stock_actual | number:'1.0-2' }} {{ item.unidad }}</td><td class="px-5 py-3">{{ predictionValue(item) | number:'1.0-2' }} {{ item.unidad }}</td><td class="px-5 py-3 font-medium">{{ item.compra_recomendada | number:'1.0-2' }} {{ item.unidad }}</td><td class="px-5 py-3"><span class="rounded-full px-2 py-1 text-xs font-medium" [ngClass]="item.estado === 'REQUIERE_COMPRA' ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700'">{{ item.estado === 'REQUIERE_COMPRA' ? 'Requiere compra' : 'Stock suficiente' }}</span></td></tr></tbody></table></div></section>
    </section>
    <ng-template #empty><section class="border border-dashed border-brand-wood/20 bg-white px-6 py-16 text-center"><lucide-icon name="brain-circuit" [size]="40" class="mx-auto text-brand-terra"></lucide-icon><h3 class="mt-3 font-bold text-brand-dark">{{ loading ? 'Cargando información predictiva...' : 'No hay información para mostrar' }}</h3><p class="mt-1 text-sm text-gray-500">{{ loading ? 'Consultando los resultados guardados.' : 'Ejecuta el proceso predictivo desde la sección Predicciones.' }}</p></section></ng-template>
  </div>`
})
export class DashboardComponent implements OnInit {
  private readonly api = inject(PredictionDashboardService); private readonly auth = inject(AuthService);
  data: PredictionDashboard | null = null; dates: string[] = []; selectedDate = ''; selectedHorizon: PredictionHorizon = 14; horizons: PredictionHorizon[] = [3, 7, 14]; health = DOWN; loading = true; updating = false; error = ''; safetyMargin = 0.1;
  get isAdmin() { return this.auth.hasRole('ADMINISTRADOR'); }
  get chartItems() { return [...(this.data?.consumo_por_insumo ?? [])].sort((a, b) => this.predictionValue(b) - this.predictionValue(a)).slice(0, 8); }
  ngOnInit() { this.api.getDates().subscribe({ next: dates => { this.dates = dates; this.selectedDate = dates[0] || ''; this.loadDashboard(); }, error: () => { this.loading = false; this.error = 'No fue posible obtener las predicciones guardadas.'; } }); this.api.getHealth().pipe(catchError(() => of(DOWN))).subscribe(value => this.health = value); }
  selectHorizon(horizon: PredictionHorizon) { this.selectedHorizon = horizon; this.loadDashboard(); }
  loadDashboard() { if (!this.selectedDate) { this.loading = false; return; } this.loading = true; this.error = ''; this.api.getDashboard(this.selectedDate, this.selectedHorizon).pipe(finalize(() => this.loading = false)).subscribe({ next: data => { this.data = data; this.safetyMargin = data.margen_seguridad; }, error: error => this.error = this.errorMessage(error, 'cargar el dashboard') }); }
  updatePredictions() { if (!this.isAdmin || !this.selectedDate) return; this.updating = true; this.error = ''; this.api.run(this.selectedDate, this.safetyMargin).pipe(switchMap(() => forkJoin({ data: this.api.getDashboard(this.selectedDate, this.selectedHorizon), dates: this.api.getDates(), health: this.api.getHealth().pipe(catchError(() => of(DOWN)))})), finalize(() => this.updating = false)).subscribe({ next: result => { this.data = result.data; this.dates = result.dates; this.health = result.health; this.safetyMargin = result.data.margen_seguridad; }, error: error => this.error = this.errorMessage(error, 'actualizar las predicciones') }); }
  predictionValue(item: SupplyRecommendation) { return this.selectedHorizon === 3 ? item.prediccion_3_dias : this.selectedHorizon === 7 ? item.prediccion_7_dias : item.prediccion_14_dias; }
  barHeight(value: number) { const maximum = Math.max(...this.chartItems.flatMap(row => [row.prediccion_3_dias, row.prediccion_7_dias, row.prediccion_14_dias]), 1); return value / maximum * 100; }
  get supplyTotal() { return (this.data?.estado_abastecimiento.requieren_compra ?? 0) + (this.data?.estado_abastecimiento.stock_suficiente ?? 0); }
  get purchasePercent() { return this.supplyTotal ? (this.data?.estado_abastecimiento.requieren_compra ?? 0) / this.supplyTotal * 100 : 0; }
  get sufficientPercent() { return 100 - this.purchasePercent; }
  get donutBackground() { return `conic-gradient(#ef4444 0 ${this.purchasePercent}%, #22c55e ${this.purchasePercent}% 100%)`; }
  formatDate(date: string) { const [year, month, day] = date.split('-'); return `${day}/${month}/${year}`; }
  exportCsv() { if (!this.selectedDate) return; this.api.exportCsv(this.selectedDate, this.selectedHorizon).subscribe({ next: blob => this.download(blob, `recomendaciones-${this.selectedDate}.csv`), error: error => this.error = this.errorMessage(error, 'exportar el reporte') }); }
  private download(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
  private errorMessage(error: any, action: string) { const message = error?.error?.message; if (error?.status === 403) return 'Tu usuario no tiene permisos para ejecutar esta operación.'; return message || `No fue posible ${action}. Verifica que Spring Boot y FastAPI estén disponibles.`; }
}
